### PR TITLE
Replaced event-stream with direct dependency

### PR DESCRIPTION
**Pull request by Basa0**
es.map is a direct use of the map-stream package

### CODE REVIEW

**Comment by simonua** [comment]
This solution fixes #11 in a more elegant way rather than pinning a specific version of _event-stream_.

**Comment by simonua** [comment]
Hi @tracker1, if you can review and complete this PR, we can immediately use it in [gulp-angular-templatecache#168](https://github.com/miickel/gulp-angular-templatecache/pull/168).

Thank you!

**Comment by DanielRuf** [comment]
It's from the same author so it makes not much difference. But the real difference is, that `event-stream` is now owned by `npmjs` so there is a less risk, that something happens.

**Comment by tracker1** [comment]
I'll try and look through this tomorrow evening... Will probably pin the version as suggested for a patch release, then do a full version release with the dependency change.  Other input welcome.

**Comment by simonua** [comment]
@tracker1, awesome! Pinning the version in the interim gives us the assurance we need for _gulp-angular-templatecache_. I'll stay tuned for an updated package and will subsequently complete the aforementioned PR. Thanks very much!

@DanielRuf, you have a very good point regarding npm ownership, I think. That lends immediate credibility. One approach is not necessarily better than the other, but what made me favor getting rid of _event-stream_ entirely are these thoughts:

- _event-stream_ now has a stigma. For someone to understand that [3.3.6](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident) was the nefarious package they heard or read about may be less applicable than for someone to simply think they ought to stay away from anything with event-stream entirely. 
- Even though the same author is involved here, pinning the version of the replacements is as applicable as pinning the version of _event-stream_. You're right in that the versions are locked after 24 hrs (and can then only be removed with npm's help (_left-pad_, anyone?))
- _event-stream_ is a bit of a grab-bag with some added functionality, it appears. Sort of loosely reminds of me _gulp-util_, which the ecosystem rid itself of mostly, if not entirely. Using one or two individual packages is better than installing the entire grab bag module (so long as that is not negated by another package in your module using _event-stream_...).

**Comment by simonua** [comment]
Hi @tracker1, have you had a chance to look at this yet, please?

Thank you!

**Comment by tracker1** [comment]
Published gulp-footer@2.0.2

**Comment by tracker1** [comment]
@simonua @Basa0 @DanielRuf Sorry for the delay, this had slipped my mind.

**Comment by simonua** [comment]
No problem at all, @tracker1! Appreciate your time and follow-up. Thank you!

**Pull request merged**
